name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'scripts/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/deploy-backend.yml'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: technofame-api
  SERVICE_NAME: api
  COMPOSE_FILE: /opt/deploy/docker-compose.yml
  LOCAL_HEALTH_URL: http://127.0.0.1:8000/healthz
  PUBLIC_HEALTH_URL: https://api.technofame.store/healthz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: backend-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image ref (lowercase owner)
        id: meta
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lc=$OWNER_LC" >> "$GITHUB_OUTPUT"
          echo "image=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Docker metadata (tags + labels)
        id: dmeta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.meta.outputs.image }}
          tags: |
            type=raw,value=latest
            type=sha
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Пушим ПО ТЕГАМ (без push-by-digest), но digest забираем из outputs
      - name: Build & Push image (by tags)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.dmeta.outputs.tags }}
          labels: ${{ steps.dmeta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image digest
        run: |
          echo "Image:  ${{ steps.meta.outputs.image }}"
          echo "Digest: ${{ steps.build.outputs.digest }}"

      # ================== DEPLOY ==================
      # Авто-детект sudo и docker compose на сервере, деплой по digest
      - name: Deploy on server (pull image@digest + recreate)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            IMAGE="${{ steps.meta.outputs.image }}@${{ steps.build.outputs.digest }}"
            COMPOSE_FILE="${{ env.COMPOSE_FILE }}"
            SERVICE="${{ env.SERVICE_NAME }}"

            # ---- SUDO DETECT ----
            SUDO=""
            if docker info >/dev/null 2>&1; then
              SUDO=""
            elif sudo -n docker info >/dev/null 2>&1; then
              SUDO="sudo -n "
            else
              echo "ERROR: No permission to access Docker daemon. Options:"
              echo "  1) Add user to 'docker' group: sudo usermod -aG docker $USER && newgrp docker"
              echo "  2) Allow passwordless sudo for docker: visudo (NOPASSWD)"
              exit 1
            fi

            # ---- COMPOSE DETECT ----
            if ${SUDO}docker compose version >/dev/null 2>&1; then
              COMPOSE="${SUDO}docker compose"
            elif ${SUDO}docker-compose version >/dev/null 2>&1; then
              COMPOSE="${SUDO}docker-compose"
            else
              echo "ERROR: docker compose not found"
              exit 1
            fi

            echo "[deploy] Pull image by digest: ${IMAGE}"
            ${SUDO}docker pull "${IMAGE}"

            # Если образ приватный и на сервере нет логина в GHCR:
            # ${SUDO}docker login ghcr.io -u "${{ secrets.GHCR_USER }}" -p "${{ secrets.GHCR_PAT }}"

            echo "[deploy] Update service: ${SERVICE}"
            # Вариант A: образ прописан в compose (по тегу). Тогда обычный pull/up:
            ${COMPOSE} -f "${COMPOSE_FILE}" pull "${SERVICE}" || true
            ${COMPOSE} -f "${COMPOSE_FILE}" up -d --force-recreate "${SERVICE}"

            echo "[deploy] ps:"
            ${COMPOSE} -f "${COMPOSE_FILE}" ps

            echo "[deploy] last logs (tail 120):"
            ${COMPOSE} -f "${COMPOSE_FILE}" logs --no-color -n 120 "${SERVICE}" || true

      # ЛОКАЛЬНЫЙ health-check (минует внешний прокси)
      - name: Container health check (server localhost)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            # SUDO DETECT для curl через 127.0.0.1 не нужен, но оставим для единообразия
            url="${{ env.LOCAL_HEALTH_URL }}"
            for i in {1..24}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" "$url" || true)
              echo "Attempt $i: $url -> HTTP $code"
              if [ "$code" = "200" ]; then
                exit 0
              fi
              sleep 5
            done
            echo "Local container health check failed"
            exit 1

      # ПУБЛИЧНЫЙ health-check через HTTPS/прокси
      - name: Public HTTPS health check
        run: |
          set -euo pipefail
          url="${{ env.PUBLIC_HEALTH_URL }}"
          for i in {1..24}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "$url" || true)
            echo "Attempt $i: $url -> HTTP $code"
            if [ "$code" = "200" ]; then
              exit 0
            fi
            sleep 5
          done
          echo "Public health check failed"
          exit 1
