name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - "app/**"
      - "scripts/**"
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/deploy-backend.yml"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: technofame-api
  SERVICE_NAME: api
  # Используем актуальный override-файл
  COMPOSE_FILE: /opt/apps/backend/scripts/docker-compose.override.yml
  PUBLIC_HEALTH_URL: https://api.technofame.store/healthz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: backend-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image ref (lowercase owner)
        id: meta
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lc=$OWNER_LC" >> "$GITHUB_OUTPUT"
          echo "image=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Docker metadata (tags + labels)
        id: dmeta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.meta.outputs.image }}
          tags: |
            type=raw,value=latest
            type=sha
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image (by tags)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.dmeta.outputs.tags }}
          labels: ${{ steps.dmeta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show image digest
        run: |
          echo "Image:  ${{ steps.meta.outputs.image }}"
          echo "Digest: ${{ steps.build.outputs.digest }}"

      # ================== DEPLOY ==================
      - name: Deploy on server (pull image@digest + recreate)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            IMAGE="${{ steps.meta.outputs.image }}@${{ steps.build.outputs.digest }}"
            SERVICE="${{ env.SERVICE_NAME }}"
            FILE="${{ env.COMPOSE_FILE }}"

            echo "[deploy] compose file: ${FILE}"
            if [ ! -f "${FILE}" ]; then
              echo "ERROR: compose file not found: ${FILE}"
              exit 2
            fi

            # ---- SUDO DETECT ----
            SUDO=""
            if docker info >/dev/null 2>&1; then
              SUDO=""
            elif sudo -n docker info >/dev/null 2>&1; then
              SUDO="sudo -n "
            else
              echo "ERROR: No permission to access Docker daemon."
              exit 1
            fi

            # ---- COMPOSE DETECT ----
            if ${SUDO}docker compose version >/dev/null 2>&1; then
              COMPOSE="${SUDO}docker compose"
            elif ${SUDO}docker-compose version >/dev/null 2>&1; then
              COMPOSE="${SUDO}docker-compose"
            else
              echo "ERROR: docker compose not found"
              exit 1
            fi

            echo "[deploy] docker pull ${IMAGE}"
            ${SUDO}docker pull "${IMAGE}"

            # Override только image на точный digest (без сложных here-doc)
            TMP_OVERRIDE="$(mktemp)"
            printf "services:\n  %s:\n    image: %s\n" "${SERVICE}" "${IMAGE}" > "${TMP_OVERRIDE}"

            set -x
            ${COMPOSE} -f "${FILE}" -f "${TMP_OVERRIDE}" up -d --force-recreate "${SERVICE}"
            set +x
            rm -f "${TMP_OVERRIDE}"

            echo "[deploy] ps:"
            ${COMPOSE} -f "${FILE}" ps || true

            echo "[deploy] last logs (tail 120):"
            ${COMPOSE} -f "${FILE}" logs --no-color -n 120 "${SERVICE}" || true

      - name: Container health check (server localhost via mapped port)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            SERVICE="${{ env.SERVICE_NAME }}"
            FILE="${{ env.COMPOSE_FILE }}"
            TARGET_CONTAINER_PORT=8000

            # SUDO + COMPOSE detect
            SUDO=""
            if docker info >/dev/null 2>&1; then
              SUDO=""
            elif sudo -n docker info >/dev/null 2>&1; then
              SUDO="sudo -n "
            else
              echo "ERROR: No permission to access Docker daemon."
              exit 1
            fi
            if ${SUDO}docker compose version >/dev/null 2>&1; then
              COMPOSE="${SUDO}docker compose"
            elif ${SUDO}docker-compose version >/dev/null 2>&1; then
              COMPOSE="${SUDO}docker-compose"
            else
              echo "ERROR: docker compose not found"
              exit 1
            fi

            HOST_PORT="$(${COMPOSE} -f "${FILE}" port "${SERVICE}" ${TARGET_CONTAINER_PORT} 2>/dev/null | tail -n1 | awk -F: '{print $NF}')"
            if [ -z "${HOST_PORT:-}" ]; then
              echo "WARN: can't detect mapped port for ${SERVICE}/${TARGET_CONTAINER_PORT}, fallback to 127.0.0.1:${TARGET_CONTAINER_PORT}"
              HOST_PORT="${TARGET_CONTAINER_PORT}"
            fi

            URL="http://127.0.0.1:${HOST_PORT}/healthz"
            echo "[health] probing ${URL}"

            for i in {1..24}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
              echo "Attempt $i: $URL -> HTTP $code"
              if [ "$code" = "200" ]; then
                exit 0
              fi
              sleep 5
            done
            echo "Local container health check failed"
            exit 1

      - name: Public HTTPS health check
        run: |
          set -euo pipefail
          url="${{ env.PUBLIC_HEALTH_URL }}"
          for i in {1..24}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "$url" || true)
            echo "Attempt $i: $url -> HTTP $code"
            if [ "$code" = "200" ]; then
              exit 0
            fi
            sleep 5
          done
          echo "Public health check failed"
          exit 1
