name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'scripts/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/deploy-backend.yml'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: technofame-api
  SERVICE_NAME: api
  COMPOSE_FILE: /opt/deploy/docker-compose.yml
  LOCAL_HEALTH_URL: http://127.0.0.1:8000/healthz
  PUBLIC_HEALTH_URL: https://api.technofame.store/healthz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: backend-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image ref (lowercase owner)
        id: meta
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner_lc=$OWNER_LC" >> "$GITHUB_OUTPUT"
          echo "image=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Docker metadata (tags + labels)
        id: dmeta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.meta.outputs.image }}
          tags: |
            type=raw,value=latest
            type=sha
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ВАЖНО: никаких outputs: push-by-digest=true здесь не используем, чтобы не конфликтовать с tags
      - name: Build & Push image (by tags)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.dmeta.outputs.tags }}
          labels: ${{ steps.dmeta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # при необходимости укажите платформу; по умолчанию текущая:
          # platforms: linux/amd64

      - name: Show image digest
        run: |
          echo "Image:  ${{ steps.meta.outputs.image }}"
          echo "Digest: ${{ steps.build.outputs.digest }}"

      # === DEPLOY ===
      - name: Deploy on server (pull image@digest + recreate)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            IMAGE="${{ steps.meta.outputs.image }}@${{ steps.build.outputs.digest }}"
            COMPOSE="${{ env.COMPOSE_FILE }}"
            SERVICE="${{ env.SERVICE_NAME }}"

            echo "[deploy] docker pull ${IMAGE}"
            # Если образ приватный — заранее выполнен docker login ghcr.io (PAT c read:packages)
            docker pull "${IMAGE}"

            echo "[deploy] update service ${SERVICE}"
            # Вариант A: образ зашит в compose -> обычный pull/up:
            docker compose -f "${COMPOSE}" pull "${SERVICE}" || true
            docker compose -f "${COMPOSE}" up -d --force-recreate "${SERVICE}"

            echo "[deploy] ps:"
            docker compose -f "${COMPOSE}" ps

            echo "[deploy] last logs (tail 120):"
            docker compose -f "${COMPOSE}" logs --no-color -n 120 "${SERVICE}" || true

      - name: Container health check (server localhost)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail
            url="${{ env.LOCAL_HEALTH_URL }}"
            for i in {1..24}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" "$url" || true)
              echo "Attempt $i: $url -> HTTP $code"
              if [ "$code" = "200" ]; then
                exit 0
              fi
              sleep 5
            done
            echo "Local container health check failed"
            exit 1

      - name: Public HTTPS health check
        run: |
          set -euo pipefail
          url="${{ env.PUBLIC_HEALTH_URL }}"
          for i in {1..24}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "$url" || true)
            echo "Attempt $i: $url -> HTTP $code"
            if [ "$code" = "200" ]; then
              exit 0
            fi
            sleep 5
          end
          echo "Public health check failed"
          exit 1
