name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'scripts/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/deploy-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: meta
        shell: bash
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/technofame-api"
          echo "lower=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.lower }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            sudo -n /opt/deploy/deploy_api.sh

      - name: Post-deploy health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            echo "--- check API locally (bypass Caddy) ---"
            code_local=$(curl -sk -o /dev/null -w "%{http_code}" http://127.0.0.1:18000/healthz || true)
            echo "local healthz HTTP $code_local"
            if [ "$code_local" != "200" ]; then
              echo "API not healthy locally. Showing docker info..."
              sudo -n /usr/bin/docker ps || true
              sudo -n /usr/bin/docker logs --tail=200 scripts-api-1 || true
              exit 1
            fi

            echo "--- check via Caddy (edge) ---"
            code_edge=$(curl -sk -o /dev/null -w "%{http_code}" https://api.technofame.store/healthz || true)
            echo "edge healthz HTTP $code_edge"
            if [ "$code_edge" != "200" ]; then
              echo "Caddy returns $code_edge, showing caddy status/logs:"
              sudo -n systemctl status caddy --no-pager || true
              sudo -n journalctl -u caddy -n 120 --no-pager || true
              exit 1
            fi

            echo "--- CORS sanity (one allow-origin) ---"
            curl -ski -H "Origin: https://technofame.store" https://api.technofame.store/api/v1/categories \
              | grep -i '^access-control-allow-origin' || true

            echo "OK"
